"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

type Status = "PENDING" | "COVERED";
type Dormitory = { building: { id: string; name: string; school: { id: string; name: string } }; floor: string; id: string; roomNo: string };
type RecordRow = { agent: { id: string; name: string }; agentId: string; dormitory: Dormitory; id: string; note: string | null; status: Status; updatedAt: Date };
type AuditRow = { action: "CREATE" | "UPDATE" | "DELETE"; afterNote: string | null; afterStatus: Status | null; agent: { id: string; name: string }; beforeNote: string | null; beforeStatus: Status | null; createdAt: Date; dormitory: Dormitory; id: string; operator: { id: string; name: string }; recordId: string };

function statusLabel(status: Status | null) { return status === "COVERED" ? "已覆盖" : status === "PENDING" ? "待补扫" : "无"; }

export function SweepDataManager({ audits, records }: { audits: AuditRow[]; records: RecordRow[] }) {
  const router = useRouter();
  const [tab, setTab] = useState<"records" | "audits">("records");
  const [schoolId, setSchoolId] = useState(""); const [buildingId, setBuildingId] = useState(""); const [roomNo, setRoomNo] = useState(""); const [agentId, setAgentId] = useState(""); const [status, setStatus] = useState("");
  const [editing, setEditing] = useState<RecordRow | null>(null); const [deleting, setDeleting] = useState<RecordRow | null>(null); const [editStatus, setEditStatus] = useState<Status>("PENDING"); const [editNote, setEditNote] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const schools = useMemo(() => [...new Map(records.map(row => [row.dormitory.building.school.id, row.dormitory.building.school])).values()], [records]);
  const buildings = useMemo(() => [...new Map(records.filter(row => !schoolId || row.dormitory.building.school.id === schoolId).map(row => [row.dormitory.building.id, row.dormitory.building])).values()], [records, schoolId]);
  const agents = useMemo(() => [...new Map(records.map(row => [row.agent.id, row.agent])).values()], [records]);
  const matches = (row: { agent: { id: string }; dormitory: Dormitory; afterStatus?: Status | null; beforeStatus?: Status | null; status?: Status }) => (!schoolId || row.dormitory.building.school.id === schoolId) && (!buildingId || row.dormitory.building.id === buildingId) && (!roomNo || row.dormitory.roomNo.includes(roomNo)) && (!agentId || row.agent.id === agentId) && (!status || row.status === status || row.afterStatus === status || row.beforeStatus === status);
  const visibleRecords = records.filter(matches); const visibleAudits = audits.filter(matches);

  function openEdit(record: RecordRow) { setEditing(record); setEditStatus(record.status); setEditNote(record.note ?? ""); setMessage(""); }
  async function request(url: string, init: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); if (!response.ok) { const result = await response.json().catch(() => null) as { error?: { message?: string } } | null; throw new Error(result?.error?.message ?? "操作失败，请稍后重试"); } }
  async function saveEdit() { if (!editing) return; setSaving(true); setMessage(""); try { await request(`/api/admin/sweep-records/${editing.id}`, { body: JSON.stringify({ customNote: editNote.trim() || null, status: editStatus }), method: "PUT" }); setEditing(null); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setSaving(false); } }
  async function confirmDelete() { if (!deleting) return; setSaving(true); setMessage(""); try { await request(`/api/admin/sweep-records/${deleting.id}`, { method: "DELETE" }); setDeleting(null); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "删除失败"); } finally { setSaving(false); } }

  return <div className="sweep-data-manager">
    <div className="dialog-tabs" role="tablist"><button aria-selected={tab === "records"} onClick={() => setTab("records")} role="tab" type="button">当前记录</button><button aria-selected={tab === "audits"} onClick={() => setTab("audits")} role="tab" type="button">审计记录</button></div>
    <div className="sweep-filters"><label>学校<select aria-label="学校" onChange={event => { setSchoolId(event.target.value); setBuildingId(""); }} value={schoolId}><option value="">全部学校</option>{schools.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>楼栋<select aria-label="楼栋" onChange={event => setBuildingId(event.target.value)} value={buildingId}><option value="">全部楼栋</option>{buildings.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>房号<input aria-label="房号" onChange={event => setRoomNo(event.target.value)} value={roomNo} /></label><label>代理<select aria-label="代理" onChange={event => setAgentId(event.target.value)} value={agentId}><option value="">全部代理</option>{agents.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>状态<select aria-label="状态" onChange={event => setStatus(event.target.value)} value={status}><option value="">全部状态</option><option value="PENDING">待补扫</option><option value="COVERED">已覆盖</option></select></label></div>
    {tab === "records" ? <div className="sweep-data-list">{visibleRecords.map(record => <article className="sweep-data-row" key={record.id}><div><strong>{record.dormitory.building.school.name} · {record.dormitory.building.name} · {record.dormitory.roomNo}</strong><span>{record.agent.name} · {statusLabel(record.status)}</span><p>{record.note ?? "无备注"}</p><time>{new Date(record.updatedAt).toLocaleString("zh-CN")}</time></div><div className="row-actions"><button aria-label={`编辑 ${record.dormitory.roomNo}`} className="quiet-button" onClick={() => openEdit(record)} type="button">编辑</button><button aria-label={`删除 ${record.dormitory.roomNo}`} className="danger-button" onClick={() => setDeleting(record)} type="button">删除</button></div></article>)}</div> : <div><p className="access-warning">审计记录只读，不可修改或删除</p><div className="sweep-data-list">{visibleAudits.map(audit => <article className="sweep-data-row audit-row" key={audit.id}><div><strong>{audit.dormitory.building.name} · {audit.dormitory.roomNo} · {audit.agent.name}</strong><span>{audit.action} · 操作人 {audit.operator.name}</span><p>{audit.beforeNote ?? "无备注"} → {audit.afterNote ?? "无备注"}</p><small>{statusLabel(audit.beforeStatus)} → {statusLabel(audit.afterStatus)}</small><time>{new Date(audit.createdAt).toLocaleString("zh-CN")}</time></div></article>)}</div></div>}
    {editing ? <div className="dialog-backdrop" role="presentation"><section aria-label="编辑扫楼记录" className="campus-dialog" role="dialog"><div className="dialog-header"><h2>编辑 {editing.dormitory.roomNo}</h2><button className="icon-button" onClick={() => setEditing(null)} type="button">×</button></div><div className="dialog-body admin-form"><div className="record-status-tabs"><button aria-pressed={editStatus === "PENDING"} onClick={() => setEditStatus("PENDING")} type="button">待补扫</button><button aria-pressed={editStatus === "COVERED"} onClick={() => setEditStatus("COVERED")} type="button">已覆盖</button></div><label>管理员备注<textarea aria-label="管理员备注" maxLength={60} onChange={event => setEditNote(event.target.value)} value={editNote} /></label><p className="form-error">{message}</p><button className="primary-button" disabled={saving} onClick={saveEdit} type="button">{saving ? "保存中…" : "保存修改"}</button></div></section></div> : null}
    {deleting ? <div className="dialog-backdrop" role="presentation"><section aria-label="确认删除" className="campus-dialog" role="alertdialog"><div className="dialog-header"><h2>确认删除 {deleting.dormitory.roomNo}</h2></div><div className="dialog-body admin-form"><p className="access-warning">删除后只能从审计记录追溯，不能恢复当前记录。</p><p className="form-error">{message}</p><button className="danger-button" disabled={saving} onClick={confirmDelete} type="button">确认永久删除</button><button className="quiet-button" disabled={saving} onClick={() => setDeleting(null)} type="button">取消</button></div></section></div> : null}
  </div>;
}
