$ErrorActionPreference = 'Stop'

$prototypePath = Join-Path $PSScriptRoot '..\docs\prototype\campus-sweep-saas-prototype.html'
$html = Get-Content -Raw -LiteralPath $prototypePath
$failures = [System.Collections.Generic.List[string]]::new()

function Assert-Contains {
    param(
        [string]$Pattern,
        [string]$Message
    )

    if ($html -notmatch $Pattern) {
        $failures.Add($Message)
    }
}

Assert-Contains '\.back\{[^}]*background:#eef1f4' 'Back buttons must use a light-gray background.'
Assert-Contains '\.back\{[^}]*min-height:48px' 'Back buttons must have a minimum 48px tap height.'
Assert-Contains '\.back\{[^}]*border-radius:12px' 'Back buttons must use rounded rectangles.'
Assert-Contains 'id="login"' 'The prototype must provide one shared login page.'
Assert-Contains 'class="login-card"' 'Login must use a focused responsive card.'
Assert-Contains 'data-login-username' 'Login must collect a username.'
Assert-Contains 'data-login-password' 'Login must collect a password.'
Assert-Contains 'data-login-password-toggle' 'Login must allow the password to be shown or hidden.'
Assert-Contains 'data-login-submit' 'Login must provide one shared submit action.'
Assert-Contains 'data-login-error="credentials"' 'Login must show a generic credentials error without exposing account existence.'
Assert-Contains 'data-login-error="disabled"' 'Disabled agents must receive an explicit contact-the-administrator message.'
Assert-Contains "role==='admin'\?'admin':'school'" 'Successful login must route administrators to admin and agents to school selection.'
Assert-Contains 'wireLogin\(' 'The shared login page must wire its password toggle and role-based redirect.'
Assert-Contains "searchParams\.get\('loginState'\)" 'The prototype must support direct review of login error states.'
Assert-Contains 'body\[data-scene="login"\] \.intro\{display:none\}' 'The login form must remain above the fold by hiding the prototype intro only on login.'
Assert-Contains 'document\.body\.dataset\.scene=id' 'Scene navigation must expose the active scene for login-specific responsive layout.'
Assert-Contains 'data-record-editor="single"' 'Single-record creation must use the shared save-feedback contract.'
Assert-Contains 'wireRecordEditors\(' 'All three record flows must share one interactive editor controller.'
Assert-Contains 'renderRecordEditor\(' 'Status, quick-note, custom-note, and save states must render together.'
Assert-Contains 'data-custom-note-input' 'Every record flow must provide an inline custom-note input.'
Assert-Contains 'data-status="pending"' 'Record editors must expose the pending status as a real control value.'
Assert-Contains 'data-status="covered"' 'Record editors must expose the covered status as a real control value.'
Assert-Contains '<h3[^>]*>记录 202</h3>[\s\S]*当前代理 × 202' 'The single-record title and explanatory copy must refer to the same dormitory.'
Assert-Contains 'data-record-editor="edit"' 'Record editing must use the shared save-feedback contract.'
Assert-Contains 'data-record-editor="batch"[^>]*data-batch-atomic="true"' 'Batch saving must be explicitly all-or-nothing.'
Assert-Contains 'data-batch-flow="two-step"' 'Batch marking must use one phone with a two-step flow.'
Assert-Contains 'data-batch-step="select"' 'Batch marking must provide a dormitory-selection step.'
Assert-Contains 'data-batch-step="edit"' 'Batch marking must provide a shared record-editing step.'
Assert-Contains 'data-batch-room' 'Batch dormitories must expose interactive selection controls.'
Assert-Contains 'data-batch-next' 'Batch selection must expose a next-step action.'
Assert-Contains 'data-batch-selection-title' 'Batch selection must show the live selected count.'
Assert-Contains 'data-batch-edit-title' 'Batch editing must list the exact selected dormitories.'
Assert-Contains 'data-batch-back-to-selection' 'Batch editing must allow returning without losing the selection.'
Assert-Contains 'showBatchStep\(' 'Batch marking must switch between selection and editing in the same phone.'
Assert-Contains 'updateBatchSelection\(' 'Batch room changes must update counts, titles, and save copy together.'
Assert-Contains "searchParams\.get\('batchStep'\)" 'The prototype must support direct review of each batch step.'
Assert-Contains 'data-save-flow="single"' 'Single-record creation must expose a save action.'
Assert-Contains 'data-save-flow="edit"' 'Record editing must expose a save action.'
Assert-Contains 'data-save-flow="batch"' 'Batch marking must expose a save action.'
Assert-Contains 'data-save-feedback' 'Every record editor must keep save feedback in the current page.'
Assert-Contains 'setSaveState\(' 'Save actions must share one state transition function.'
Assert-Contains 'wireSaveFeedback\(' 'Save actions must wire saving, success, and failure feedback consistently.'
Assert-Contains "button\.disabled=state==='saving'" 'Saving must temporarily prevent duplicate submissions.'
Assert-Contains 'data-offline-queue="none"' 'A failed save must explicitly remain online-only without an offline queue.'
Assert-Contains 'beforeunload' 'Leaving with unsaved record changes must trigger a discard warning.'
Assert-Contains 'data-discard-dialog' 'Internal navigation with unsaved record changes must use a focused discard dialog.'
Assert-Contains 'data-discard-cancel' 'The discard dialog must allow the agent to continue editing.'
Assert-Contains 'data-discard-confirm' 'The discard dialog must allow the agent to discard changes and continue navigation.'
Assert-Contains 'requestSceneChange\(' 'All internal scene navigation must pass through the unsaved-change guard.'
Assert-Contains 'resetActiveRecordEditor\(' 'Discarding changes must reset the active single, edit, or batch record editor.'
Assert-Contains 'pendingSceneTarget' 'Discard confirmation must remember the exact page the agent intended to open.'
Assert-Contains "document\.querySelectorAll\('\.nav \[data-scene\]'\)" 'Scene click handlers must be scoped to navigation buttons and never attached to the body.'
Assert-Contains "searchParams\.get\('navigationState'\)" 'The prototype must support direct review of the unsaved-navigation dialog.'
Assert-Contains "searchParams\.get\('saveState'\)" 'The prototype must support direct review of save feedback states.'
Assert-Contains "searchParams\.get\('saveFlow'\)" 'The prototype must support direct review of each save flow.'
Assert-Contains 'data-session-menu' 'Authenticated pages must expose one compact identity menu.'
Assert-Contains 'data-session-name' 'The identity menu must show the current user name.'
Assert-Contains 'data-session-role' 'The identity menu must show whether the user is an agent or administrator.'
Assert-Contains 'data-session-logout' 'The identity menu must provide a logout action.'
Assert-Contains 'data-session-dialog' 'Logout and interrupted sessions must share one focused dialog.'
Assert-Contains 'data-session-state="expired"' 'The prototype must explain that an expired session requires a new login.'
Assert-Contains 'data-session-state="disabled"' 'A disabled signed-in account must be returned to login with a clear explanation.'
Assert-Contains 'data-session-state="access-revoked"' 'Revoked school access must return the agent to school selection without logging out.'
Assert-Contains 'wireSessionControls\(' 'Identity, logout, and interrupted-session behavior must be wired together.'
Assert-Contains 'window\.hasUnsavedRecordChanges' 'Logout must inspect unsaved record changes before leaving.'
Assert-Contains "querySelector\('\[data-login-password\]'\)\.value=''" 'Returning to login must clear the password field.'
Assert-Contains "searchParams\.get\('sessionState'\)" 'The prototype must support direct review of interrupted-session states.'
Assert-Contains 'data-view-page="school"' 'The school list must support loading, empty, and error states.'
Assert-Contains 'data-view-page="building"' 'The building list must support loading, empty, and error states.'
Assert-Contains 'data-view-page="matrix"' 'The dormitory matrix must support loading, empty, and error states.'
Assert-Contains 'data-view-content' 'Agent data pages must separate loaded content from fallback states.'
Assert-Contains 'data-view-state-host' 'Agent data pages must expose one shared visible-state host.'
Assert-Contains 'data-loading-skeleton' 'Loading states must use a compact skeleton instead of appearing blank.'
Assert-Contains 'data-view-state-action' 'Recoverable empty and error states must provide a large action button.'
Assert-Contains 'data-offline-cache="none"' 'Load failures must not silently display stale offline data.'
Assert-Contains 'setAgentViewState\(' 'School, building, and matrix states must share one renderer.'
Assert-Contains 'wireAgentViewStates\(' 'Retry behavior must be wired for all agent data pages.'
Assert-Contains "searchParams\.get\('viewPage'\)" 'The prototype must support direct review of a state on a selected page.'
Assert-Contains "searchParams\.get\('viewState'\)" 'The prototype must support direct review of loading, empty, and error states.'
Assert-Contains 'id="history"' 'Dormitory history must be an independent page instead of a second phone inside details.'
Assert-Contains 'data-jump="history"' 'The dormitory detail page must provide a full-row history entry.'
Assert-Contains '<button class="linkrow"[^>]*data-jump="history"' 'The full-row history entry must be an accessible button.'
Assert-Contains 'data-history-latest-only="true"' 'Agent history must show only each agent current latest result, never status trajectories.'
Assert-Contains 'id="history"[\s\S]*data-jump="detail"' 'The history page must provide a large return action to the dormitory detail page.'
Assert-Contains 'data-detail-records="mine-only"' 'The dormitory detail page must keep only the current agent record.'

Assert-Contains 'id="building"' 'A dedicated building selection page is required.'
Assert-Contains 'class="building-card"[^>]*data-jump="matrix"' 'A full building card must open the matrix.'
Assert-Contains 'class="building-progress"' 'Building cards must show coverage progress.'
Assert-Contains 'class="building-counts"' 'Building cards must show covered, pending, and unvisited counts.'

$buildingCardCount = ([regex]::Matches($html, 'class="building-card"')).Count
if ($buildingCardCount -lt 3) {
    $failures.Add("The building page must show at least 3 buildings; found $buildingCardCount.")
}

Assert-Contains 'class="admin-data-tree"' 'Admin basic data must use a nested data tree.'
Assert-Contains 'class="tree-node school-node"' 'The data tree must have school accordions.'
Assert-Contains 'class="admin-building-card"' 'School accordions must contain clickable building cards.'
Assert-Contains 'data-open-blueprint="3"' 'Clicking a building card must open its dormitory blueprint.'
Assert-Contains 'data-action="add-school"' 'The school level must provide an add-school action.'
Assert-Contains 'data-action="edit-building-name"' 'Buildings must support renaming.'
Assert-Contains 'data-action="edit-building-note"' 'Buildings must support optional notes.'
Assert-Contains 'data-action="dormitory-management"' 'Building menus must provide one centralized dormitory-management entry.'
Assert-Contains 'data-menu-trigger="school"' 'School cards must expose a three-dot action menu.'
Assert-Contains 'data-menu-trigger="building"' 'Building cards must expose a three-dot action menu.'
Assert-Contains 'class="context-menu school-menu"' 'The school action menu must be a compact popover.'
Assert-Contains 'class="context-menu building-menu"' 'The building action menu must be a compact popover.'
Assert-Contains 'data-action="edit-school-name"' 'School menus must support renaming.'
Assert-Contains 'data-action="delete-or-disable-school"' 'School menus must combine safe delete and disable.'
Assert-Contains 'data-action="delete-or-disable-building"' 'Building menus must combine safe delete and disable.'
Assert-Contains 'event\.stopPropagation\(\)' 'Opening a three-dot menu must not toggle its accordion.'
Assert-Contains "event\.key==='Escape'" 'The open action menu must close when Escape is pressed.'

$nativeMenuCount = ([regex]::Matches($html, '<details class="menu-shell">')).Count
if ($nativeMenuCount -lt 21) {
    $failures.Add("Every school, building, agent, quick-note, and sweep-record action menu must use an independent native disclosure; found only $nativeMenuCount.")
}

if ($html -match 'class="floor-node"|data-menu-trigger="dormitory"|class="context-menu dormitory-menu"') {
    $failures.Add('Floor accordions and floor-level dormitory action menus must be removed.')
}

Assert-Contains 'data-protected="true"' 'Dormitories with sweep records must be protected from deletion.'
Assert-Contains 'data-delete-policy="children-disable"' 'Schools and buildings with children must be protected from deletion.'
Assert-Contains 'URLSearchParams\(window\.location\.search\)' 'The prototype must support direct scene links for review.'
Assert-Contains "searchParams\.get\('menu'\)" 'The prototype must support direct-open action menus for visual review.'
Assert-Contains 'id="adminModal"[^>]*role="dialog"' 'Admin menu actions must open one shared accessible dialog.'
Assert-Contains 'id="admin-form-add-school"' 'The add-school action must have a form.'
Assert-Contains 'id="admin-form-edit-school-name"' 'The edit-school action must have a form.'
Assert-Contains 'id="admin-form-add-building"' 'The add-building action must have a form.'
Assert-Contains 'id="admin-form-edit-building-name"' 'The edit-building action must have a form.'
Assert-Contains 'id="admin-form-edit-building-note"' 'The building-note action must have a form.'
Assert-Contains 'id="admin-form-add-dorm-single"' 'The single-dorm action must have a form.'
Assert-Contains 'id="admin-form-add-dorm-batch"' 'The batch-dorm action must have a form.'
Assert-Contains 'id="admin-form-dormitory-management"' 'Centralized dormitory management must have a unified form.'
Assert-Contains 'data-dorm-manager-tab="single"' 'Dormitory management must provide single-add mode.'
Assert-Contains 'data-dorm-manager-tab="batch"' 'Dormitory management must provide batch-add mode.'
Assert-Contains 'data-dorm-manager-tab="delete"' 'Dormitory management must provide delete-or-disable mode.'
Assert-Contains 'data-dorm-manager-summary' 'Dormitory management must summarize delete versus disable results.'
Assert-Contains 'id="admin-form-delete-or-disable"' 'Delete-or-disable actions must have a confirmation view.'
Assert-Contains 'data-batch-preview' 'Batch dorm creation must show a generated-room preview.'
Assert-Contains "searchParams\.get\('action'\)" 'The prototype must support direct-open admin action dialogs for review.'
Assert-Contains "searchParams\.get\('managerTab'\)" 'The prototype must support direct-open dormitory-management tabs for review.'
Assert-Contains 'openAdminModal\(actionName' 'Admin actions must use the shared dialog without changing accordion context.'
Assert-Contains 'id="blueprintModal"[^>]*role="dialog"' 'A building blueprint must open in an accessible dialog.'
Assert-Contains 'class="blueprint-floor"[^>]*data-floor="2"' 'The blueprint must group dormitories by floor without accordions.'
Assert-Contains 'class="blueprint-room protected"[^>]*data-protected="true"' 'The blueprint must show rooms protected by sweep records.'
Assert-Contains 'data-room-state="active"' 'The blueprint must distinguish active rooms.'
Assert-Contains 'openBlueprint\(buildingId' 'Building cards must open the blueprint without navigating away.'
Assert-Contains 'renderBlueprintRooms\(buildingId' 'Each building blueprint must render its own room structure.'
Assert-Contains 'data-blueprint-note=' 'Each building blueprint must use the selected building note.'
Assert-Contains "searchParams\.get\('blueprint'\)" 'The prototype must support direct-open blueprints for review.'
Assert-Contains 'class="module wide agent-module"' 'Agent and school access management must use a full-width module.'
Assert-Contains 'class="agent-list"' 'The administrator must see agents in one scan-friendly list.'
Assert-Contains 'data-agent-id="zhang-san"[^>]*data-agent-status="active"' 'Active agents must expose their current account state.'
Assert-Contains 'data-agent-id="wang-wu"[^>]*data-agent-status="disabled"' 'Disabled agents must remain visible to the administrator.'
Assert-Contains 'data-menu-trigger="agent"' 'Every agent must expose a compact three-dot action menu.'
Assert-Contains 'data-action="create-agent"' 'Administrators must be able to create an agent.'
Assert-Contains 'data-action="edit-agent-name"' 'Administrators must be able to rename an agent.'
Assert-Contains 'data-action="configure-agent-schools"' 'Administrators must be able to configure school access.'
Assert-Contains 'data-action="reset-agent-password"' 'Administrators must be able to reset an agent password.'
Assert-Contains 'data-action="toggle-agent-status"' 'Administrators must be able to disable or enable an agent.'
Assert-Contains 'id="admin-form-create-agent"' 'Agent creation must use the shared admin dialog.'
Assert-Contains 'id="admin-form-create-agent".*data-generated-password hidden' 'Initial passwords must remain hidden until agent creation succeeds.'
Assert-Contains 'id="admin-form-configure-agent-schools"' 'School access configuration must use the shared admin dialog.'
Assert-Contains 'data-school-access="school-main"' 'School access configuration must list the main campus explicitly.'
Assert-Contains 'data-school-access="school-dushuhu"' 'School access configuration must list the Dushuhu campus explicitly.'
Assert-Contains 'data-generated-password' 'Generated passwords must be displayed in a dedicated one-time field.'
Assert-Contains 'data-copy-password' 'Generated passwords must offer a copy action.'
Assert-Contains "copied\?'已复制':'请手动复制'" 'Copy controls must not claim success when clipboard access fails.'
Assert-Contains '\.password-output\[hidden\]\{display:none\}' 'Reset passwords must remain hidden until the administrator confirms the reset.'
Assert-Contains 'revealResetPassword\(' 'Password reset confirmation must reveal the generated password without closing the dialog.'
Assert-Contains 'revealCreatedAgentPassword\(' 'Agent creation must reveal the one-time initial password only after confirmation.'
Assert-Contains "searchParams\.get\('agent'\)" 'The prototype must support direct-open agent dialogs for visual review.'
Assert-Contains "searchParams\.get\('passwordRevealed'\)" 'The prototype must support direct review of the post-reset password state.'
Assert-Contains "searchParams\.get\('agentCreated'\)" 'The prototype must support direct review of the post-create password state.'
Assert-Contains 'class="module wide quick-note-module"' 'Quick notes must use a full-width admin module.'
Assert-Contains 'data-quick-note-tab="pending"' 'Quick-note management must separate pending notes.'
Assert-Contains 'data-quick-note-tab="covered"' 'Quick-note management must separate covered notes.'
Assert-Contains 'data-quick-note-panel="pending"' 'Pending quick notes must have their own management panel.'
Assert-Contains 'data-quick-note-panel="covered"' 'Covered quick notes must have their own management panel.'
Assert-Contains 'data-note-id="pending-no-answer"' 'Quick-note rows must have stable identities.'
Assert-Contains 'data-note-move="up"' 'Administrators must be able to move notes upward.'
Assert-Contains 'data-note-move="down"' 'Administrators must be able to move notes downward.'
Assert-Contains 'data-action="add-quick-note"' 'Administrators must be able to add quick notes.'
Assert-Contains 'data-action="edit-quick-note"' 'Administrators must be able to edit quick notes.'
Assert-Contains 'data-action="toggle-quick-note"' 'Administrators must be able to enable or disable quick notes.'
Assert-Contains 'data-action="delete-quick-note"' 'Administrators must be able to delete quick notes.'
Assert-Contains 'id="admin-form-add-quick-note"' 'Quick-note creation must use the shared admin dialog.'
Assert-Contains 'id="admin-form-edit-quick-note"' 'Quick-note editing must use the shared admin dialog.'
Assert-Contains 'id="admin-form-delete-quick-note"' 'Quick-note deletion must use the shared admin dialog.'
Assert-Contains 'data-note-snapshot-policy="immutable"' 'Quick-note configuration must explicitly preserve historical record text.'
Assert-Contains 'data-system-quick-note="custom"' 'The fixed custom-note entry must be documented outside the editable list.'
Assert-Contains 'wireQuickNoteTabs\(' 'Quick-note groups must switch without leaving the admin page.'
Assert-Contains "adminToast\.textContent='原型演示：操作已确认，示例数据未改变'" 'Modal confirmation must restore the general success message after quick-note actions.'
Assert-Contains "searchParams\.get\('noteGroup'\)" 'The prototype must support direct review of either quick-note group.'
Assert-Contains "searchParams\.get\('noteId'\)" 'The prototype must support direct review of a specific quick-note action.'
Assert-Contains 'class="module wide sweep-data-module"' 'Sweep data must use a full-width admin module.'
Assert-Contains 'data-sweep-data-tab="records"' 'Sweep data must provide a current-records tab.'
Assert-Contains 'data-sweep-data-tab="audit"' 'Sweep data must provide an audit-log tab.'
Assert-Contains 'data-sweep-data-panel="records"' 'Current records must have their own panel.'
Assert-Contains 'data-sweep-data-panel="audit"' 'Audit entries must have their own read-only panel.'
Assert-Contains 'data-record-filter="school"' 'Current records must be filterable by school.'
Assert-Contains 'data-record-filter="building"' 'Current records must be filterable by building.'
Assert-Contains 'data-record-filter="room"' 'Current records must be filterable by room number.'
Assert-Contains 'data-record-filter="agent"' 'Current records must be filterable by agent.'
Assert-Contains 'data-record-filter="status"' 'Current records must be filterable by status.'
Assert-Contains 'data-sweep-record-id="record-zhang-201"' 'Current sweep records must have stable identities.'
Assert-Contains 'data-action="edit-sweep-record"' 'Administrators must be able to correct a current sweep record.'
Assert-Contains 'data-action="delete-sweep-record"' 'Administrators must be able to remove an erroneous current sweep record.'
Assert-Contains 'id="admin-form-edit-sweep-record"' 'Sweep-record editing must use the shared admin dialog.'
Assert-Contains 'id="admin-form-delete-sweep-record"' 'Sweep-record deletion must use a second-confirmation dialog.'
Assert-Contains 'data-delete-audit-snapshot="preserved"' 'Deleting a current record must preserve its original text in the audit log.'
Assert-Contains 'data-overall-status-recalculation="required"' 'Editing or deleting a current record must recalculate the dormitory overall status.'
Assert-Contains 'data-audit-action="UPDATE"' 'The audit log must show record corrections.'
Assert-Contains 'data-audit-action="DELETE"' 'The audit log must show deleted-record snapshots.'
Assert-Contains 'class="audit-before"' 'Audit entries must show the state before an administrator change.'
Assert-Contains 'class="audit-after"' 'Audit entries must show the state after an administrator change.'
Assert-Contains 'wireSweepDataTabs\(' 'Current records and audit logs must switch without leaving the admin page.'
Assert-Contains "searchParams\.get\('dataView'\)" 'The prototype must support direct review of either sweep-data tab.'
Assert-Contains "searchParams\.get\('recordId'\)" 'The prototype must support direct review of a specific current record action.'
Assert-Contains 'data-building-card="3"[^>]*data-floor-count="1"[^>]*data-dorm-count="2"[^>]*data-count-source="dormitories"' 'Agent building cards must derive floor and dorm counts from dormitory data.'
Assert-Contains 'data-building-matrix="3"[^>]*data-floor-count="1"[^>]*data-dorm-count="2"[^>]*data-count-source="dormitories"' 'The building matrix must use the same derived counts.'
Assert-Contains 'data-matrix-room="201"' 'Matrix room 201 must be bound to the live demo state.'
Assert-Contains 'data-matrix-room="202"' 'Matrix room 202 must be bound to the live demo state.'
Assert-Contains 'data-matrix-count="covered"' 'Matrix summary counts must be rendered from current records.'
Assert-Contains 'renderSweepDemo\(' 'Saved records must re-render matrix, detail, and history views together.'
Assert-Contains 'commitRecordEditor\(' 'Successful editor saves must commit their selected rooms before returning.'
Assert-Contains 'data-detail-room' 'Dormitory detail must render the currently selected room dynamically.'
Assert-Contains 'data-building-id="3"[^>]*data-floor-count="1"[^>]*data-dorm-count="2"[^>]*data-count-source="dormitories"' 'Admin building counts must derive from dormitory data.'
Assert-Contains 'data-floor="2"' 'The 3-building example must contain the derived second-floor group.'
Assert-Contains 'data-room-no="201"' 'The 3-building example must contain room 201.'
Assert-Contains 'data-room-no="202"' 'The 3-building example must contain room 202.'

if ($html -match 'data-count-source="note"') {
    $failures.Add('Building notes must never be used as the source of counts.')
}

$blueprintFloorCount = ([regex]::Matches($html, 'class="blueprint-floor" data-floor="2"')).Count
if ($blueprintFloorCount -ne 1) {
    $failures.Add("The 3-building admin blueprint must derive exactly 1 floor; found $blueprintFloorCount.")
}

if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Error $_ -ErrorAction Continue }
    exit 1
}

Write-Host 'PASS: prototype layout contract'
