import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {BatchSelector,BuildingMatrix} from "@/modules/sweep/agent/building-matrix";

vi.mock("next/navigation",()=>({useRouter:()=>({replace:vi.fn()})}));

const matrix={building:{id:"b1",name:"3号楼",note:null},counts:{covered:1,pending:1,unvisited:1},floors:[{floor:"1",dormitories:[{floor:"1",hasMyRecord:false,id:"d1",myRecordId:null,myRecordVersion:null,overallStatus:"UNVISITED" as const,roomNo:"101",sortOrder:101},{floor:"1",hasMyRecord:false,id:"d2",myRecordId:null,myRecordVersion:null,overallStatus:"PENDING" as const,roomNo:"102",sortOrder:102},{floor:"1",hasMyRecord:true,id:"d3",myRecordId:"r3",myRecordVersion:2,overallStatus:"COVERED" as const,roomNo:"103",sortOrder:103}]}],school:{id:"s1",name:"本部"}};
describe("BuildingMatrix",()=>{
 beforeEach(()=>sessionStorage.clear());
 afterEach(()=>vi.restoreAllMocks());
 it("renders statuses, counts, star, and record routing",()=>{render(<BuildingMatrix floor="1" matrix={matrix}/>);expect(screen.getByText("1 已覆盖")).toBeInTheDocument();expect(screen.getByRole("link",{name:/101.*未扫/})).toHaveAttribute("href","/app/dormitories/d1/record?floor=1");expect(screen.getByRole("link",{name:/103.*已覆盖.*我扫过/})).toHaveAttribute("href","/app/dormitories/d3?floor=1");expect(screen.getByText("★")).toBeInTheDocument();});
 it("shows an empty building without offering batch marking",()=>{render(<BuildingMatrix floor="" matrix={{...matrix,counts:{covered:0,pending:0,unvisited:0},floors:[]}}/>);expect(screen.getByText("该楼栋还没有宿舍")).toBeInTheDocument();expect(screen.queryByRole("link",{name:"批量标记"})).not.toBeInTheDocument();});
 it("requires a selection before advancing and lists exact rooms",()=>{render(<BatchSelector buildingId="b1" floor="1" rooms={matrix.floors[0].dormitories}/>);expect(screen.getByRole("button",{name:"请先选择宿舍"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:/选择101/}));fireEvent.click(screen.getByRole("button",{name:/选择103/}));expect(screen.getByRole("heading",{name:"选择宿舍 · 2间"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"下一步 · 标记2间"}));expect(screen.getByRole("heading",{name:"标记 101、103"})).toBeInTheDocument();expect(screen.getByRole("link",{name:"返回选择"})).toBeInTheDocument();});
 it("keeps batch selection and draft while refreshed room tokens arrive",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("{}",{status:200}));const view=render(<BatchSelector buildingId="b1" floor="1" rooms={matrix.floors[0].dormitories}/>);fireEvent.click(screen.getByRole("button",{name:/选择101/}));fireEvent.click(screen.getByRole("button",{name:"下一步 · 标记1间"}));fireEvent.click(screen.getByRole("button",{name:"待补扫"}));fireEvent.click(screen.getByRole("button",{name:/快捷备注/}));fireEvent.click(screen.getByRole("option",{name:"自定义备注"}));fireEvent.change(screen.getByRole("textbox",{name:"备注"}),{target:{value:"保留的批量草稿"}});const refreshed=matrix.floors[0].dormitories.map(room=>room.id==="d1"?{...room,hasMyRecord:true,myRecordId:"r-new",myRecordVersion:2}:room);view.rerender(<BatchSelector buildingId="b1" floor="1" rooms={refreshed}/>);expect(screen.getByRole("heading",{name:"标记 101"})).toBeInTheDocument();expect(screen.getByRole("textbox",{name:"备注"})).toHaveValue("保留的批量草稿");fireEvent.click(screen.getByRole("button",{name:"保存1间宿舍"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalled());const body=JSON.parse(String((fetchMock.mock.calls[0][1] as RequestInit).body));expect(body.targets).toEqual([{dormitoryId:"d1",expectedRecordId:"r-new",expectedVersion:2}]);});
});
