import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {BatchSelector,BuildingMatrix} from "@/modules/sweep/agent/building-matrix";

const replace = vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({replace})}));

const floorOneRooms=[{floor:"1",hasMyRecord:false,id:"d1",myRecordId:null,myRecordVersion:null,overallStatus:"UNVISITED" as const,roomNo:"101",sortOrder:101},{floor:"1",hasMyRecord:false,id:"d2",myRecordId:null,myRecordVersion:null,overallStatus:"PENDING" as const,roomNo:"102",sortOrder:102},{floor:"1",hasMyRecord:true,id:"d3",myRecordId:"r3",myRecordVersion:2,overallStatus:"COVERED" as const,roomNo:"103",sortOrder:103}];
const matrix={building:{id:"b1",name:"3号楼",note:null},counts:{covered:1,pending:1,unvisited:2},floors:[{floor:"2",dormitories:[{floor:"2",hasMyRecord:false,id:"d201",myRecordId:null,myRecordVersion:null,overallStatus:"UNVISITED" as const,roomNo:"201",sortOrder:201}]},{floor:"1",dormitories:floorOneRooms}],school:{id:"s1",name:"本部"}};
describe("BuildingMatrix",()=>{
 beforeEach(()=>{sessionStorage.clear();localStorage.clear();replace.mockClear();});
 afterEach(()=>vi.restoreAllMocks());
 it("renders statuses, counts, star, and record routing",()=>{render(<BuildingMatrix floor="1" matrix={matrix}/>);expect(screen.getByText("1 已覆盖")).toBeInTheDocument();expect(screen.getByRole("link",{name:/101.*未扫/})).toHaveAttribute("href","/app/dormitories/d1/record?floor=1");expect(screen.getByRole("link",{name:/103.*已覆盖.*我扫过/})).toHaveAttribute("href","/app/dormitories/d3?floor=1");expect(screen.getByText("★")).toBeInTheDocument();});
 it("orders floors from low to high, only shows rooms from the selected floor, and remembers a newly selected floor",()=>{render(<BuildingMatrix floor="1" floorMemoryKey="sweep-floor-test" matrix={matrix}/>);const floors=screen.getAllByRole("link",{name:/^[12]楼$/});expect(floors.map(link=>link.textContent)).toEqual(["1楼","2楼"]);expect(screen.getByRole("link",{name:/101.*未扫/})).toBeInTheDocument();expect(screen.queryByRole("link",{name:/201.*未扫/})).not.toBeInTheDocument();expect(screen.getByRole("link",{name:"批量标记"})).toHaveAttribute("href","/app/buildings/b1/batch?floor=1");const secondFloor=screen.getByRole("link",{name:"2楼"});secondFloor.addEventListener("click",event=>event.preventDefault());fireEvent.click(secondFloor);expect(document.cookie).toContain("sweep-floor-test=2");});
 it("restores the remembered floor when a building is entered without a floor in its URL",async()=>{localStorage.setItem("sweep-floor-test","2");render(<BuildingMatrix floor="1" floorMemoryKey="sweep-floor-test" matrix={matrix}/>);await waitFor(()=>expect(replace).toHaveBeenCalledWith("/app/buildings/b1?floor=2"));});
 it("shows an empty building without offering batch marking",()=>{render(<BuildingMatrix floor="" matrix={{...matrix,counts:{covered:0,pending:0,unvisited:0},floors:[]}}/>);expect(screen.getByText("该楼栋还没有宿舍")).toBeInTheDocument();expect(screen.queryByRole("link",{name:"批量标记"})).not.toBeInTheDocument();});
 it("requires a selection before advancing and lists exact rooms",()=>{render(<BatchSelector buildingId="b1" floor="1" rooms={floorOneRooms}/>);expect(screen.getByRole("button",{name:"请先选择宿舍"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:/选择101/}));fireEvent.click(screen.getByRole("button",{name:/选择103/}));expect(screen.getByRole("heading",{name:"选择宿舍 · 2间"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"下一步 · 标记2间"}));expect(screen.getByRole("heading",{name:"标记 101、103"})).toBeInTheDocument();expect(screen.getByRole("link",{name:"返回选择"})).toBeInTheDocument();});
 it("keeps batch selection and draft while refreshed room tokens arrive",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("{}",{status:200}));const view=render(<BatchSelector buildingId="b1" floor="1" rooms={floorOneRooms}/>);fireEvent.click(screen.getByRole("button",{name:/选择101/}));fireEvent.click(screen.getByRole("button",{name:"下一步 · 标记1间"}));fireEvent.click(screen.getByRole("button",{name:"待补扫"}));fireEvent.click(screen.getByRole("button",{name:/快捷备注/}));fireEvent.click(screen.getByRole("option",{name:"自定义备注"}));fireEvent.change(screen.getByRole("textbox",{name:"备注"}),{target:{value:"保留的批量草稿"}});const refreshed=floorOneRooms.map(room=>room.id==="d1"?{...room,hasMyRecord:true,myRecordId:"r-new",myRecordVersion:2}:room);view.rerender(<BatchSelector buildingId="b1" floor="1" rooms={refreshed}/>);expect(screen.getByRole("heading",{name:"标记 101"})).toBeInTheDocument();expect(screen.getByRole("textbox",{name:"备注"})).toHaveValue("保留的批量草稿");fireEvent.click(screen.getByRole("button",{name:"保存1间宿舍"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalled());const body=JSON.parse(String((fetchMock.mock.calls[0][1] as RequestInit).body));expect(body.targets).toEqual([{dormitoryId:"d1",expectedRecordId:"r-new",expectedVersion:2}]);});
});
